* Emacs config
My emacs config. And I don't think it's useful for anyone but me.

** Version

Current Emacs version: 25.1

** Installation

*No more Cask!*\\
*No more install.sh!*

Just clone this repo and put '.emacs' and '.emacs.d' to ~/ and then run from emacs
#+BEGIN_SRC lisp
package-install-selected-packages
#+END_SRC

** Colors
As written in [[https://github.com/vemperor/emacs_config/blob/master/.emacs.d/global/setup-theme.el][this file]] there are 3 UI schemes using 5 color themes.

Schemes are =light=, =dark=, and =terminal=. There are three corresponding interactive functions to switch between schemes:
#+BEGIN_EXAMPLE
go-to-light
go-to-dark
go-to-terminal
#+END_EXAMPLE

=Light= scheme uses =adwaita= for emacs-client and =flatui= for standalone emacs.

=Dark= scheme uses =deeper-blue= for emacs-client and =tango-dark= for standalone emacs.

=Terminal= disables all themes to set emacs look "default".

Emacs starts with =light= scheme.

** Xdg (Gnome/KDE/etc) menu

To add Emacs Client to Xdg menu copy .local from repo to your =HOME=
directory

#+BEGIN_SRC shell
    $ cp -r path_to_repo/emacs_client/.local/ ~/
#+END_SRC

and add executable permissions for all users for .desktop file:

#+BEGIN_SRC shell
    $ chmod a+x .local/share/applications/emacsclient.desktop
#+END_SRC

** Mode-specific notes

*** Elixir
[[https://github.com/tonini/alchemist.el][Alchemist.el]] commands are configured to run inside "web" docker-compose container, however host-installed elixir is required to have [[https://company-mode.github.io/][company-mode]] completition. That's sad, actually =(
