(load "time-tracker-common")
(load "time-tracker-time")
(load "time-tracker-report-collect")

(defun time-tracker/reformat-time-range (time-range)
  (string-replace "-" " – " time-range))

(defun time-tracker/put-report-entry (report-entry)
  (org-table-goto-column 1)
  (insert (time-tracker/reformat-time-range (nth 0 report-entry)))
  (org-table-goto-column 2)
  (if (not (equal (nth 1 report-entry) "NONE")) (insert (nth 1 report-entry)))
  (org-table-goto-column 3)
  (insert (nth 2 report-entry))
  (org-table-goto-column 4)
  (insert (nth 4 report-entry)))

(defun time-tracker/put-empty-report-entry (report-entry)
  (org-table-goto-column 1)
  (insert (time-tracker/reformat-time-range (nth 0 report-entry)))
  (org-table-goto-column 2)
  (insert "—")
  (org-table-goto-column 3)
  (insert "—")
  (org-table-goto-column 4)
  (insert (nth 4 report-entry)))

(defun time-tracker/fill-day-report-entry (report-entry)
  (org-table-next-row)
  (if (not (nth 5 report-entry))
      (time-tracker/put-report-entry report-entry)
    (time-tracker/put-empty-report-entry report-entry)))

(defun time-tracker/fill-day-report-header ()
  (org-table-goto-column 1)
  (insert "Time")
  (org-table-goto-column 2)
  (insert "Jira ID")
  (org-table-goto-column 3)
  (insert "Total")
  (org-table-goto-column 4)
  (insert "Title")
  (org-table-next-row))

(defun time-tracker/remove-no-report-entries (report-entries)
  (seq-filter (lambda (entry) (not (nth 5 entry))) report-entries))

(defun time-tracker/report-get-entry-totals (report-entries)
  (mapcar (lambda (entry) (time-tracker/time-to-seconds (nth 3 entry))) report-entries))

(defun time-tracker/calculate-report-day-time-total (report-entries)
  (apply '+ (time-tracker/report-get-entry-totals (time-tracker/remove-no-report-entries report-entries))))

(defun time-tracker/put-report-time-total (report-entries)
  (org-table-next-row)
  (org-table-next-row)
  (org-table-goto-column 1)
  (insert "Total")
  (org-table-goto-column 3)
  (insert (time-tracker/format-time-jira (time-tracker/calculate-report-day-time-total report-entries))))

(defun time-tracker/put-jira-day-report-data (day-report-entries)
  (insert "** " (car day-report-entries) "\n")
  (org-table-create "4x1")
  (time-tracker/fill-day-report-header)
  (mapcar 'time-tracker/fill-day-report-entry (cdr day-report-entries))
  (time-tracker/put-report-time-total (cdr day-report-entries))
  (org-table-align)
  (end-of-buffer)
  (insert "\n\n"))

(defun time-tracker/build-jira-day-report ()
  (let ((day-report-entries (time-tracker/collect-jira-day-report-entries))
        (buffer (get-buffer-create "time-tracker-jira-report.org")))
    (with-current-buffer buffer
      (org-mode)
      (erase-buffer)
      (time-tracker/put-jira-day-report-data day-report-entries)
      (beginning-of-buffer))
    (pop-to-buffer buffer)))
