(load "time-tracker-common")
(load "time-tracker-time")
(load "time-tracker-report-collect")
(load "time-tracker-jira")

(defun time-tracker/reformat-time-range (time-range)
  (string-replace "-" " – " time-range))

(defun time-tracker/put-report-entry (report-entry &optional get-remote-data)
  (org-table-goto-column 1)
  (insert (time-tracker/reformat-time-range (alist-get 'time report-entry)))
  (org-table-goto-column 2)
  (if (not (equal (alist-get 'track-id report-entry) "NONE"))
      (insert (alist-get 'track-id report-entry)))
  (org-table-goto-column 3)
  (insert (alist-get 'total-jira report-entry))
  (org-table-goto-column 4)
  (insert (alist-get 'title report-entry))
  (when get-remote-data
    (org-table-goto-column 5)
    (insert (time-tracker/jira/worklog-status (alist-get 'jira-worklog report-entry) (alist-get 'total-jira report-entry)))))

(defun time-tracker/put-empty-report-entry (report-entry &optional get-remote-data)
  (org-table-goto-column 1)
  (insert (time-tracker/reformat-time-range (alist-get 'time report-entry)))
  (org-table-goto-column 2)
  (insert "—")
  (org-table-goto-column 3)
  (insert "—")
  (org-table-goto-column 4)
  (insert (alist-get 'title report-entry))
  (when get-remote-data
    (org-table-goto-column 5)
    (insert "—")))

(defun time-tracker/fill-day-report-entry (report-entry &optional get-remote-data)
  (org-table-next-row)
  (if (not (alist-get 'no-report report-entry))
      (time-tracker/put-report-entry report-entry get-remote-data)
    (time-tracker/put-empty-report-entry report-entry get-remote-data)))

(defun time-tracker/fill-day-report-header (&optional get-remote-data)
  (org-table-goto-column 1)
  (insert "Time")
  (org-table-goto-column 2)
  (insert "Jira ID")
  (org-table-goto-column 3)
  (insert "Total")
  (org-table-goto-column 4)
  (insert "Title")
  (when get-remote-data
    (org-table-goto-column 5)
    (insert "JIRA"))
  (org-table-next-row))

(defun time-tracker/remove-no-report-entries (report-entries)
  (seq-filter (lambda (entry) (not (alist-get 'no-report entry))) report-entries))

(defun time-tracker/report-get-entry-totals (report-entries)
  (mapcar (lambda (entry) (time-tracker/time-to-seconds (alist-get 'total entry))) report-entries))

(defun time-tracker/calculate-report-day-time-total (report-entries)
  (apply '+ (time-tracker/report-get-entry-totals (time-tracker/remove-no-report-entries report-entries))))

(defun time-tracker/put-report-time-total (report-entries)
  (org-table-next-row)
  (org-table-next-row)
  (org-table-goto-column 1)
  (insert "Total")
  (org-table-goto-column 3)
  (insert (time-tracker/format-time-jira (time-tracker/calculate-report-day-time-total report-entries))))

(defun time-tracker/put-jira-day-report-data (day-report-entries &optional get-remote-data)
  (insert "** " (car day-report-entries) "\n")
  (org-table-create "4x1")
  (time-tracker/fill-day-report-header get-remote-data)
  (mapcar (lambda (entry) (time-tracker/fill-day-report-entry entry get-remote-data)) (cdr day-report-entries))
  (time-tracker/put-report-time-total (cdr day-report-entries))
  (org-table-align)
  (end-of-buffer)
  (insert "\n\n"))

(defun time-tracker/build-jira-day-report (&optional get-remote-data)
  (let ((day-report-entries (time-tracker/collect-jira-day-report-entries get-remote-data))
        (buffer (get-buffer-create "time-tracker-jira-report.org")))
    (with-current-buffer buffer
      (org-mode)
      (erase-buffer)
      (time-tracker/put-jira-day-report-data day-report-entries get-remote-data)
      (beginning-of-buffer))
    (pop-to-buffer buffer)))
