(require 'ox-html)
(require 'cl-lib)
(load "adventurer-wiki-index")
(load "adventurer-wiki-macro")
(load "adventurer-wiki-html-secret")

(setq adventurer/wiki/script-path (file-name-directory load-file-name))
(setq org-export-allow-bind-keywords t)

(defun adventurer/wiki/write-css (settings)
  (let ((css-file-path (file-name-concat adventurer/wiki/script-path "adventurer-wiki-style.css"))
        (css-output-file-path (adventurer/wiki/output-path settings "index.css")))
    (copy-file css-file-path css-output-file-path)))

(defun adventurer/wiki/export-to-html (denote-files settings filename-in filename-out)
  "Converts org file to HTML and writes it to 'filename-out'"
  (let ((memo-denote-directory denote-directory))
    (with-temp-buffer
      (let ((org-export-with-toc nil)
            (org-export-with-title nil)
            (org-export-timestamp-file nil)
            (org-export-with-statistics-cookies nil)
            (org-export-with-properties nil)
            (org-export-with-section-numbers nil)
            (org-export-with-footnotes nil)
            (org-export-with-entities nil)
            (org-html-head "")
            (org-html-head-extra (adventurer/wiki/style-tag settings))
            (org-html-head-include-default-style nil)
            (org-html-head-include-scripts nil)
            (org-html-preamble nil)
            (org-html-postamble nil)
            (org-html-use-infojs nil)
            (org-export-filter-headline-functions (cons #'adventurer/wiki/add-spoiler-to-secret-info org-export-filter-headline-functions)))
        (insert (format "#+bind: denote-directory \"%s\"\n" memo-denote-directory))
        (insert-file-contents filename-in)
        (adventurer/wiki/macro-apply denote-files settings filename-in)
        (org-export-to-file 'html filename-out))))
  (adventurer/wiki/fix-denote-links settings filename-out))

(defun adventurer/wiki/style-tag (settings)
  (let ((css-path (file-name-concat (adventurer/wiki/get-settings-item settings "HTML-PATH") "index.css")))
    (format "<link rel=\"stylesheet\" type=\"text/css\" href=\"%s\">" css-path)))

(defun adventurer/wiki/fix-denote-links (settings filename-out)
  (with-temp-file filename-out
    (insert-file-contents filename-out)
    (goto-char (point-min))
    (while (re-search-forward "\"[a-z./]*\\([0-9]\\{8\\}T[0-9]\\{6\\}[^\"]*\\)\.html\"" nil t)
      (let* ((matched-text (match-string 1))
             (base-path (adventurer/wiki/get-settings-item settings "HTML-PATH"))
             (denote-name (save-match-data (denote-retrieve-filename-title matched-text)))
             (new-text (format "\"%s.html\"" (file-name-concat base-path denote-name))))
        (replace-match new-text t t)))))
