(defun denote-graph/collect-nodes (denote-files groups palette strikethrough)
  (denote-graph/group-nodes (mapcar #'(lambda (denote-file) (denote-graph/collect-node denote-file groups palette strikethrough)) denote-files)))

(defun denote-graph/collect-node (filename groups palette strikethrough)
  (let* ((file-type (denote-filetype-heuristics filename))
         (id (denote-retrieve-filename-identifier filename))
         (title (denote-retrieve-front-matter-title-value filename file-type))
         (group (denote-graph/node-group filename groups))
         (color (denote-graph/node-color filename palette))
         (is-strikethrough (seq-intersection (denote-extract-keywords-from-path filename) strikethrough)))
    `((id . ,id)
      (filename . ,filename)
      (title . ,title)
      (group . ,group)
      (color . ,color)
      (is-strikethrough . ,is-strikethrough))))

(defun denote-graph/node-group (filename groups)
  (let* ((keywords (denote-extract-keywords-from-path filename))
         (node-group (seq-find #'(lambda (group) (member group keywords)) groups nil)))
    node-group))

(defun denote-graph/node-color (filename palette)
  (let* ((keywords (denote-extract-keywords-from-path filename))
         (default (cons nil "none"))
         (palette-item (seq-find #'(lambda (item) (member (car item) keywords)) palette default)))
    (cdr palette-item)))

(defun denote-graph/group-nodes (nodes)
  (seq-group-by #'(lambda (node) (alist-get 'group node)) nodes))
