(load "adventurer-common")
(load "adventurer-collect")

(setq *adventurer-pathmapper-indent* 7)

(defun adventurer/build-path-mapper/append-output (output body)
  (string-join (list output body) "\n\n"))

(defun adventurer/build-path-mapper/wallpaper-path ()
  (if-let* ((wallpaper-property (org-collect-keywords '("WALLPAPER")))
            (wallpaper-value (cadar wallpaper-property)))
      wallpaper-value "wallpaper.png"))

(defun adventurer/build-path-mapper/write-wallpaper (output)
  (adventurer/build-path-mapper/append-output output (format "wallpaper = \"%s\"" (adventurer/build-path-mapper/wallpaper-path))))

(defun adventurer/build-path-mapper/render-alist-property (alist-property)
  (cond ((stringp (cdr alist-property)) (format "%s = \"%s\"" (car alist-property) (cdr alist-property)))
        (t (format "%s = %s" (car alist-property) (cdr alist-property)))))

(defun adventurer/build-path-mapper/render-alist (alist)
  (let* ((non-nil-properties (seq-filter #'(lambda (item) (cdr item)) alist))
         (rendered-properties (mapcar 'adventurer/build-path-mapper/render-alist-property non-nil-properties))
         (property-string (string-join rendered-properties ", "))
         (rendered-alist (format "{ %s }" property-string)))
    rendered-alist))

(defun adventurer/build-path-mapper/indent (string)
  (format "%s%s" (make-string *adventurer-pathmapper-indent* ? ) string))

(defun adventurer/build-path-mapper/write-urls (output)
  (if-let* ((url-property (org-collect-keywords '("URLS")))
            (url-unparsed (split-string (cadar url-property)))
            (urls (mapcar 'adventurer/parse-link url-unparsed))
            (url-strings (mapcar 'adventurer/build-path-mapper/render-alist urls))
            (url-strings (mapcar 'adventurer/build-path-mapper/indent url-strings))
            (url-string (string-join url-strings ",\n"))
            (urls-value (format "urls = [\n%s\n]" url-string))
            (output-with-urls (adventurer/build-path-mapper/append-output output urls-value)))
      output-with-urls output))

(defun adventurer/build-path-mapper/render-scene-tokens (scene)
  (let ((render-token (lambda (token) (adventurer/build-path-mapper/indent (adventurer/build-path-mapper/render-alist token)))))
    (mapcar render-token (alist-get 'tokens scene))))

(defun adventurer/build-path-mapper/render-scene-place-tokens (scene)
  (let ((render-place-token (lambda (place-token) (adventurer/build-path-mapper/indent (adventurer/build-path-mapper/render-alist place-token)))))
    (mapcar render-place-token (alist-get 'place-tokens scene))))

(defun adventurer/build-path-mapper/render-list (list)
  (if (length> list 0)
      (format "[\n%s\n]"(string-join list ",\n"))
    "[]"))

(defun adventurer/build-path-mapper/render-scene (scene)
  (let* ((scene-output "[[scenes]]")
         (scene-title (alist-get 'title scene))
         (scene-id (alist-get 'id scene))
         (scene-map (alist-get 'map scene))
         (scene-tokens (adventurer/build-path-mapper/render-scene-tokens scene))
         (scene-place-tokens (adventurer/build-path-mapper/render-scene-place-tokens scene))
         (scene-output (string-join `(,scene-output ,(format "name = \"%s\"" scene-title)) "\n"))
         (scene-output (string-join `(,scene-output "type = \"battle\"") "\n"))
         (scene-output (string-join `(,scene-output ,(format "map.file = \"%s\"" scene-map)) "\n"))
         (scene-output (string-join `(,scene-output ,(format "tokens = %s" (adventurer/build-path-mapper/render-list scene-tokens))) "\n"))
         (scene-output (string-join `(,scene-output ,(format "place_tokens = %s" (adventurer/build-path-mapper/render-list scene-place-tokens))) "\n"))
         )
    scene-output))

(defun adventurer/build-path-mapper/write-scenes (output scene-entries)
  (let* ((non-todo-scenes (seq-filter #'(lambda (scene) (not (alist-get 'todo scene))) scene-entries))
         (rendered-scenes (mapcar 'adventurer/build-path-mapper/render-scene non-todo-scenes))
         (scenes-output (string-join rendered-scenes "\n\n")))
    (adventurer/build-path-mapper/append-output output scenes-output)))

(defun adventurer/build-path-mapper/collect-scene-files (scene)
  (let* ((map-path (alist-get 'map scene))
         (tokens (alist-get 'tokens scene))
         (token-paths (mapcar #'(lambda (token) (alist-get 'image token)) tokens)))
    (cons map-path token-paths)))

(defun adventurer/build-path-mapper/collect-files (scene-entries)
  (let* ((scene-files (flatten-tree (mapcar 'adventurer/build-path-mapper/collect-scene-files scene-entries)))
         (wallpaper-path (adventurer/build-path-mapper/wallpaper-path))
         (files (cons wallpaper-path scene-files)))
    (seq-uniq files)))

(defun adventurer/build-path-mapper/pack (files)
  (let ((file-list (string-join (mapcar #'(lambda (file) (format "\"%s\"" file)) files) " "))
        (output-filename (adventurer/compose-filename "zip")))
    (copy-file (adventurer/compose-filename "toml") "manifest.toml")
    (delete-file output-filename)
    (shell-command (format "/usr/bin/zip \"%s\" %s \"manifest.toml\" %s" output-filename file-list (adventurer/ignore-shell-output)))
    (delete-file "manifest.toml")))

(defun adventurer/build-path-mapper/clear ()
  (delete-file (adventurer/compose-filename "toml"))
  (delete-file "manifest.toml")
  (delete-file (adventurer/compose-filename "zip")))

(defun adventurer/build-path-mapper (scene-entries)
  (let* ((output (format "title = \"%s\"" (org-get-title)))
         (output (adventurer/build-path-mapper/write-wallpaper output))
         (output (adventurer/build-path-mapper/write-urls output))
         (output (adventurer/build-path-mapper/write-scenes output scene-entries))
         (files (adventurer/build-path-mapper/collect-files scene-entries)))
    (write-region output nil (adventurer/compose-filename "toml"))
    (adventurer/build-path-mapper/pack files)))
